import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import FontAwesomeConfig from "./fontawesome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "KeenKeeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" className={`h-full`}>
      <head>
        <FontAwesomeConfig/>
      </head>



      <body className="min-h-full flex flex-col bg-[#F8FAFC]">

        <Navbar/>
        {children}
        <Footer/>


      </body>
    </html>
  );
}
